### ISSUE TITLE
Path to virtual environment script

### ISSUE THREAD

**Issue by Arnou1** [nova-python/Python.novaextension#2]
Sorry for the noob question, but may I ask what path should I fill in the Script section for the Virtual Environment task? I tried absolute/relative paths of my Python/Shell scripts, but the task report keeps telling me that the file does not exist.

**Comment by dcwatson** [comment]
The path should be relative to the workspace directory. However, if you're trying to run a script outside of your workspace, I realize it may not be constructing the path correctly -- I'll fix that. If you are trying to run a script inside your workspace, I guess I'd check that you've set a Python Interpreter in the Python extension settings for your workspace?

**Comment by dcwatson** [comment]
You'll also want to make sure the script is executable. The task tries to run it directly, not running it as an argument to `python` or `sh` or anything.

**Comment by Arnou1** [comment]
> You'll also want to make sure the script is executable. The task tries to run it directly, not running it as an argument to `python` or `sh` or anything.

Thanks a lot! I can now run my script by making it executable.
