### ISSUE TITLE
No command found with the name "python.resolveEnvs"

### ISSUE THREAD

**Issue by SteveMcGrath** [nova-python/Python.novaextension#9]
I keep running into this issue with the extension...

![CleanShot 2024-09-19 at 14 37 31](https://github.com/user-attachments/assets/e3b34974-9758-4e26-9447-dbc2172568cf)

**Comment by dcwatson** [comment]
Where are you running into this error?

**Comment by SteveMcGrath** [comment]
On the extension setting page.  Every time I scroll to the top it'll throw that error.  It also just dies when trying to run ruff on save.

**Comment by dcwatson** [comment]
If you open the extension console (Extensions → Show Extension Console), do you see anything in the logs?

**Comment by SteveMcGrath** [comment]
```
Extension encountered an uncaught exception:
/Users/steve/Library/Application Support/Nova/Extensions/net.danwatson.Python/Scripts/main.js (Line 59, Column 17)
TypeError: null is not an object (evaluating 'venvDirs.unshift')
    @file:///Users/steve/Library/Application%20Support/Nova/Extensions/net.danwatson.Python/Scripts/main.js:59:17
```

**Comment by dcwatson** [comment]
Thank you! I just pushed out an update that should hopefully fix this. Please let me know if it doesn't.

**Comment by SteveMcGrath** [comment]
no more errors after the update!  thanks again for the plugin, its been a real lifesaver for me.
